// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SavePointAPI.Models;

#nullable disable

namespace SavePointAPI.Migrations
{
    [DbContext(typeof(SavePointContext))]
    [Migration("20240506030717_SavePointGame")]
    partial class SavePointGame
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SavePointAPI.Models.SavePointGame", b =>
                {
                    b.Property<int>("SavePointGameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SavePointGameId"));

                    b.Property<string>("GameConsole")
                        .HasColumnType("text");

                    b.Property<string>("GameDescription")
                        .HasColumnType("text");

                    b.Property<string>("GameDeveloper")
                        .HasColumnType("text");

                    b.Property<string>("GameGenre")
                        .HasColumnType("text");

                    b.Property<string>("GameImage")
                        .HasColumnType("text");

                    b.Property<string>("GameName")
                        .HasColumnType("text");

                    b.Property<string>("GamePublisher")
                        .HasColumnType("text");

                    b.Property<string>("GameRating")
                        .HasColumnType("text");

                    b.Property<string>("GameReleaseDate")
                        .HasColumnType("text");

                    b.HasKey("SavePointGameId");

                    b.ToTable("SavePointGames");
                });

            modelBuilder.Entity("SavePointAPI.Models.SavePointNote", b =>
                {
                    b.Property<int>("SavePointNoteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SavePointNoteId"));

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<DateOnly>("NoteDate")
                        .HasColumnType("date");

                    b.Property<int>("SavePointGameId")
                        .HasColumnType("integer");

                    b.HasKey("SavePointNoteId");

                    b.HasIndex("SavePointGameId");

                    b.ToTable("SavePointNotes");
                });

            modelBuilder.Entity("SavePointAPI.Models.SavePointNote", b =>
                {
                    b.HasOne("SavePointAPI.Models.SavePointGame", "SavePointGame")
                        .WithMany()
                        .HasForeignKey("SavePointGameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SavePointGame");
                });
#pragma warning restore 612, 618
        }
    }
}
